name: Dream On Publish
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install & deploy global
        run: |
          yarn install --frozen-lockfile
          yarn deploy:global
          yarn deploy:conference
      - name: Upload global public dir
        uses: actions/upload-artifact@v1
        with:
          name: global
          path: apps/global/public
      - name: Upload conference public dir
        uses: actions/upload-artifact@v1
        with:
          name: conference
          path: apps/conference/public
        env:
          CI: true
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download global public dir
        uses: actions/download-artifact@v1
        with:
          name: global
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'public'
          remoteDir: 'public_html'
      - uses: actions/checkout@v1
      - name: Download conference public dir
        uses: actions/download-artifact@v1
        with:
          name: conference
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'public'
          remoteDir: 'conference.dreamon.world'
